# Generated by Django 3.2.12 on 2022-04-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Enter a category name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=1)),
                ('pic_url', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('energy', models.IntegerField(default=0)),
                ('carbo', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('fat', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('proteins', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('sodium', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('fiber', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='off.category', verbose_name='related category')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replaced_id', to='off.product')),
                ('replacement_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='replacing_id', to='off.product')),
            ],
        ),
    ]
