# Generated by Django 3.2.9 on 2022-04-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('off', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='replacement_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='replacing_id', to='off.product'),
        ),
    ]
