# Generated by Django 3.2.9 on 2021-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
