# Generated by Django 3.2.9 on 2022-04-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('off', '0003_product_fiber2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fiber2',
        ),
    ]
