# Generated by Django 3.2.9 on 2021-11-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off', '0004_auto_20211126_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=200),
        ),
    ]
