# Generated by Django 3.2.9 on 2021-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='sodium',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='g', max_length=2),
        ),
    ]
