# Generated by Django 3.2.9 on 2021-12-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('off', '0008_remove_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pic_small_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic_thumb_url',
        ),
    ]
