"""
Django settings for django_p8 project.


Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

from .config.settings import DEBUG, SECRET_KEY

# import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-t46%tfpu&dh868*%$f_cl-!5t1qiv=ycwbv)l*ud&@t6^%20p%"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = ["pur_beurre_974.herokuapp.com","127.0.0.1",
                 "testserver", "localhost", "whitenoise.runserver_nostalgic"]




# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django_dumpdata_one",
    "nutella",
    "off",
    "users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "whitenoise.storage.CompressedManifestStaticFilesStorage"
]

ROOT_URLCONF = "django_p8.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_p8.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "nutella",
        "USER": "slb",
        "PASSWORD": "jade",
        "HOST": "localhost",
        "PORT": "",
    }
}

# db_from_env = dj_database_url.config(conn_max_age=600)
# DATABASES["default"].update(db_from_env)



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Indian/Reunion"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = [BASE_DIR / "static"]
# STATICFILES_STORAGE="whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "index"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

if DEBUG:
    INTERNAL_IPS = ('127.0.0.1', 'localhost',)

    # MIDDLEWARE += (
    #             'debug_toolbar.middleware.DebugToolbarMiddleware',
    #             )

    # INSTALLED_APPS += (
    #             'debug_toolbar',
    #             )


    # DEBUG_TOOLBAR_PANELS = [
    #             'debug_toolbar.panels.versions.VersionsPanel',
    #             'debug_toolbar.panels.timer.TimerPanel',
    #             'debug_toolbar.panels.settings.SettingsPanel',
    #             'debug_toolbar.panels.headers.HeadersPanel',
    #             'debug_toolbar.panels.request.RequestPanel',
    #             'debug_toolbar.panels.sql.SQLPanel',
    #             'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    #             'debug_toolbar.panels.templates.TemplatesPanel',
    #             'debug_toolbar.panels.cache.CachePanel',
    #             'debug_toolbar.panels.signals.SignalsPanel',
    #             'debug_toolbar.panels.logging.LoggingPanel',
    #             'debug_toolbar.panels.redirects.RedirectsPanel',
    #             'debug_toolbar.panels.profiling.ProfilingPanel',
    # ]

    # DEBUG_TOOLBAR_CONFIG = {
    #             'INTERCEPT_REDIRECTS': False,
    #     }
    
    # import mimetypes
    # mimetypes.add_type("application/javascript", ".js", True)

TESTS_SHOW_BROWSER = True
